sonar.organization=codeurjc-students
sonar.projectKey=codeurjc-students_2026-PCMod
sonar.projectName=2026-PCMod

sonar.sources=backend/pcmod/src/main/java,frontend/app
sonar.java.binaries=backend/pcmod/target/classes

sonar.coverage.jacoco.xmlReportPaths=backend/pcmod/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=backend/pcmod/target/**,backend/**/PcmodApplication.java,backend/**/SpaRoutingConfig.java,frontend/node_modules/**,frontend/dist/**,frontend/build/**,frontend/app/components/header.tsx,frontend/app/components/footer.tsx,frontend/app/routes/home.tsx,frontend/app/app.css,frontend/app/root.tsx,frontend/app/routes.ts
sonar.qualitygate.wait=true