sonar.organization=codeurjc_students
sonar.projectKey=codeurjc-students_2026-PCMod
sonar.projectName=2026-PCMod

sonar.sources=backend/pcmod/src/main/java,frontend/app
sonar.java.binaries=backend/pcmod/target/classes

sonar.coverage.jacoco.xmlReportPaths=backend/pcmod/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=backend/pcmod/target/**,frontend/node_modules/**,frontend/dist/**,frontend/build/**
sonar.qualitygate.wait=true